

CREATE DATABASE AlojamientosDavidMartin
USE AlojamientosDavidMartin
GO

-- 1. CREAR TABLAS (Sin FKs iniciales)

CREATE TABLE CATEGORIAS(
    IDCATEGORIA SMALLINT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE_CATEGORIA NVARCHAR(50) NOT NULL
)
CREATE UNIQUE INDEX IX_NOM_CATEGORIA ON CATEGORIAS(NOMBRE_CATEGORIA)


CREATE TABLE ESTABLECIMIENTOS(
    IDESTABLECIMIENTO SMALLINT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE_COMERCIAL NVARCHAR(100) NOT NULL,
    DIRECCION NVARCHAR(150) NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL,
    EMAIL NVARCHAR(100) NULL,
    IDCATEGORIA SMALLINT NOT NULL
)
CREATE INDEX IX_NOM_ESTABLECIMIENTO ON ESTABLECIMIENTOS(NOMBRE_COMERCIAL)


CREATE TABLE UNIDADES_ALOJAMIENTO(
    IDESTABLECIMIENTO SMALLINT NOT NULL,
    NUMERO SMALLINT NOT NULL,
    NOMBRE_UNIDAD NVARCHAR(50) NULL,
    CAPACIDAD_MAX SMALLINT NOT NULL CHECK (CAPACIDAD_MAX > 0),
    ESTADO VARCHAR(15) NOT NULL CHECK (ESTADO IN ('Disponible', 'Ocupada', 'Mantenimiento')),
    PRECIO_NOCHE SMALLMONEY NOT NULL CHECK (PRECIO_NOCHE > 0),
    DESCRIPCION NVARCHAR(MAX) NULL
)
ALTER TABLE UNIDADES_ALOJAMIENTO
ADD CONSTRAINT PK_UNIDADES PRIMARY KEY (IDESTABLECIMIENTO, NUMERO)


CREATE TABLE CLIENTES(
    IDCLIENTE INT IDENTITY(1,1) PRIMARY KEY,
    DNI_NIE CHAR(9) UNIQUE NOT NULL,
    NOMBRE NVARCHAR(40) NOT NULL,
    APELLIDOS NVARCHAR(80) NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL,
    EMAIL NVARCHAR(100) NULL
)
CREATE INDEX IX_CLIENTE_APELLIDOS ON CLIENTES(APELLIDOS, NOMBRE)


CREATE TABLE RESERVAS(
    IDRESERVA INT IDENTITY(1,1) PRIMARY KEY,
    IDESTABLECIMIENTO SMALLINT NOT NULL,
    NUMERO_UNIDAD SMALLINT NOT NULL,
    IDCLIENTE INT NOT NULL,
    FECHA_CREACION DATETIME DEFAULT GETDATE() NOT NULL,
    FECHA_ENTRADA DATETIME NOT NULL,
    FECHA_SALIDA DATETIME NOT NULL,
    CANTIDAD_PERSONAS SMALLINT NOT NULL,
    ESTADO_RESERVA VARCHAR(15) NOT NULL CHECK (ESTADO_RESERVA IN ('Pendiente', 'Confirmada', 'Cancelada', 'Finalizada')),
    FIANZA SMALLMONEY NULL,
    IMPORTE_ESTIMADO SMALLMONEY NOT NULL,
    CONSTRAINT CK_FECHAS CHECK (FECHA_SALIDA > FECHA_ENTRADA)
)


CREATE TABLE PAGOS(
    IDPAGO INT IDENTITY(1,1) PRIMARY KEY,
    IDRESERVA INT NOT NULL,
    IMPORTE SMALLMONEY NOT NULL CHECK (IMPORTE > 0),
    FECHA_PAGO DATETIME NULL,
    METODO_PAGO NVARCHAR(30) NOT NULL
)

-- 2. DEFINICIÓN DE FOREIGN KEYS (ALTER TABLE)

-- Establecimiento pertenece a una Categoría
ALTER TABLE ESTABLECIMIENTOS
ADD CONSTRAINT FK_ESTABLEC_CATEG FOREIGN KEY (IDCATEGORIA)
REFERENCES CATEGORIAS(IDCATEGORIA)

-- Unidad de Alojamiento pertenece a un Establecimiento
ALTER TABLE UNIDADES_ALOJAMIENTO
ADD CONSTRAINT FK_UNIDAD_ESTABLEC FOREIGN KEY (IDESTABLECIMIENTO)
REFERENCES ESTABLECIMIENTOS(IDESTABLECIMIENTO)

-- Reserva asociada a una Unidad (Clave compuesta)
ALTER TABLE RESERVAS
ADD CONSTRAINT FK_RESERVA_UNIDAD FOREIGN KEY (IDESTABLECIMIENTO, NUMERO_UNIDAD)
REFERENCES UNIDADES_ALOJAMIENTO(IDESTABLECIMIENTO, NUMERO)

-- Reserva asociada a un Cliente
ALTER TABLE RESERVAS
ADD CONSTRAINT FK_RESERVA_CLIENTE FOREIGN KEY (IDCLIENTE)
REFERENCES CLIENTES(IDCLIENTE)

-- Pago asociado a una Reserva
ALTER TABLE PAGOS
ADD CONSTRAINT FK_PAGO_RESERVA FOREIGN KEY (IDRESERVA)
REFERENCES RESERVAS(IDRESERVA)