//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIDADES_ALOJAMIENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UNIDADES_ALOJAMIENTO()
        {
            this.RESERVAS = new HashSet<RESERVA>();
        }
    
        public short IDESTABLECIMIENTO { get; set; }
        public short NUMERO { get; set; }
        public string NOMBRE_UNIDAD { get; set; }
        public short CAPACIDAD_MAX { get; set; }
        public string ESTADO { get; set; }
        public decimal PRECIO_NOCHE { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ESTABLECIMIENTO ESTABLECIMIENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVA> RESERVAS { get; set; }
    }
}
