//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlojamientosDavidMartinEntities : DbContext
    {
        public AlojamientosDavidMartinEntities()
            : base("name=AlojamientosDavidMartinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORIA> CATEGORIAS { get; set; }
        public virtual DbSet<CLIENTE> CLIENTES { get; set; }
        public virtual DbSet<ESTABLECIMIENTO> ESTABLECIMIENTOS { get; set; }
        public virtual DbSet<PAGO> PAGOS { get; set; }
        public virtual DbSet<RESERVA> RESERVAS { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UNIDADES_ALOJAMIENTO> UNIDADES_ALOJAMIENTO { get; set; }
    }
}
