//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        public int IDPAGO { get; set; }
        public int IDRESERVA { get; set; }
        public decimal IMPORTE { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO { get; set; }
        public string METODO_PAGO { get; set; }
    
        public virtual RESERVA RESERVA { get; set; }
    }
}
