//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESERVA()
        {
            this.PAGOS = new HashSet<PAGO>();
        }
    
        public int IDRESERVA { get; set; }
        public short IDESTABLECIMIENTO { get; set; }
        public short NUMERO_UNIDAD { get; set; }
        public int IDCLIENTE { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public System.DateTime FECHA_ENTRADA { get; set; }
        public System.DateTime FECHA_SALIDA { get; set; }
        public short CANTIDAD_PERSONAS { get; set; }
        public string ESTADO_RESERVA { get; set; }
        public Nullable<decimal> FIANZA { get; set; }
        public decimal IMPORTE_ESTIMADO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAGO> PAGOS { get; set; }
        public virtual UNIDADES_ALOJAMIENTO UNIDADES_ALOJAMIENTO { get; set; }
    }
}
